FROM python:3.9

# set the workdir
WORKDIR /root

# minimal software stack
RUN apt-get update; apt-get clean
RUN apt-get install -y nano less htop git; apt-get clean

# update pip
RUN pip install --no-cache-dir --upgrade pip

# install base software
RUN pip install --no-cache-dir ipython

# python software stack
Run pip install --no-cache-dir six
Run pip install --no-cache-dir flake8
RUN pip install --no-cache-dir numpy
RUN pip install --no-cache-dir scipy
RUN pip install --no-cache-dir matplotlib
RUN pip install --no-cache-dir pandas
RUN pip install --no-cache-dir numexpr
RUN pip install --no-cache-dir jupyterlab
RUN pip install --no-cache-dir notebook
RUN pip install --no-cache-dir scikit-learn
RUN pip install --no-cache-dir scikit-optimize
RUN pip install --no-cache-dir tensorflow
RUN pip install --no-cache-dir xgboost

# install cmsml from master
RUN git clone https://github.com/cms-ml/cmsml.git && \
    cd cmsml && \
    pip install --no-cache-dir . && \
    cd .. && \
    rm -rf cmsml
