FROM python:3.8

# set the workdir
WORKDIR /root

# minimal software stack
RUN apt-get update; apt-get clean
RUN apt-get install -y nano less htop git; apt-get clean

# python software stack
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir --upgrade ipython
RUN pip install --no-cache-dir \
    flake8 \
    numpy \
    scipy \
    matplotlib \
    pandas \
    numexpr \
    jupyterlab \
    notebook \
    scikit-learn \
    scikit-optimize \
    tensorflow \
    xgboost \
    scinum

# install cmsml from master
RUN git clone https://github.com/cms-ml/cmsml.git && \
    cd cmsml && \
    pip install --no-cache-dir . && \
    cd .. && \
    rm -rf cmsml

# initial command
CMD ["bash", "-i", "-l"]
